# Generated by Django 4.2.7 on 2023-11-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_wearing_delete_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='wearing',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='wearing',
            name='date',
            field=models.DateField(verbose_name='Date Worn'),
        ),
    ]
