# Generated by Django 4.2.7 on 2023-11-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_accessory_alter_wearing_options_alter_wearing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessory'),
        ),
    ]
